In [77]:
#Task 1: Data Cleaning and Preprocessing
#Objective: Clean and prepare a raw dataset (with nulls, duplicates, inconsistent formats).
#Tools: Python (Pandas)
#Deliverables: Cleaned dataset + short summary of changes
#Hints / Mini Guide:
#1) Identify and handle missing values using .isnull() in Python.
#2) Remove duplicate rows using .drop_duplicates() - not necessary since I wanted to retain the values and filled the values using ".fillna"
#3) Standardize text values like gender, country names, etc.
#4) Convert date formats to a consistent type (e.g., dd-mm-yyyy).
#5) Rename column headers to be clean and uniform (e.g., lowercase, no spaces).
#6) Check and fix data types (e.g., age should be int, date as datetime).
#Dataset used: Netflix Movies and TV Shows

In [78]:
import pandas as pd
import numpy as np 
#loading the dataset 
df=pd.read_csv("C:\\Users\\admin\\OneDrive\\Desktop\\Elevate Labs\\netflix_titles.csv")
#using ".shpae" to get a clean tabular format 
print(df.shape)
df.head() #first 5 rows of the dataset is displayed

(8807, 12)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [79]:
#1)
#to detect the number of null values present in the dataset
print(df.isnull())
print("\n")
#to have an approximate count of the number of null values in the dataset
print(df.isnull().sum())

      show_id   type  title  director   cast  country  date_added  \
0       False  False  False     False   True    False       False
1       False  False  False      True  False    False       False
2       False  False  False     False  False     True       False
3       False  False  False      True   True     True       False
4       False  False  False      True  False    False       False
...       ...    ...    ...       ...    ...      ...         ...
8802    False  False  False     False  False    False       False
8803    False  False  False      True   True     True       False
8804    False  False  False     False  False    False       False
8805    False  False  False     False  False    False       False
8806    False  False  False     False  False    False       False

      release_year  rating  duration  listed_in  description
0            False   False     False      False        False
1            False   False     False      False        False
2            False   False     False      False        False
3            False   False     False      False        False
4            False   False     False      False        False
...            ...     ...       ...        ...          ...
8802         False   False     False      False        False
8803         False   False     False      False        False
8804         False   False     False      False        False
8805         False   False     False      False        False
8806         False   False     False      False        False

[8807 rows x 12 columns]


show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [80]:
#to check if it is okay to drop a whole column due to the number of null values
missing_percentage = df["director"].isnull().mean() * 100
print(f"Percentage of missing values in 'director': {missing_percentage:.2f}%")

Percentage of missing values in 'director': 29.91%

In [81]:
#since it is between 25-75% it would be wise to retain the colummn and replace the null values with "Unknown"
columns_to_fill = ["director", "cast", "country",]
df[columns_to_fill] = df[columns_to_fill].fillna("Not Specified")
print(df.isnull().sum())

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64

In [82]:
#fixing the null values of the date_added column
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['date_added'] = df['date_added'].ffill()
print("Missing values in 'date_added' after filling:")
print(df['date_added'].isnull().sum())

Missing values in 'date_added' after filling:
0

In [83]:
#5)
#converting the column headers to upper case
df.columns = df.columns.str.upper()
print("\nNew column names (in uppercase):")
print(df.columns)

New column names (in uppercase):
Index(['SHOW_ID', 'TYPE', 'TITLE', 'DIRECTOR', 'CAST', 'COUNTRY', 'DATE_ADDED',
       'RELEASE_YEAR', 'RATING', 'DURATION', 'LISTED_IN', 'DESCRIPTION'],
      dtype='object')

In [84]:
#4)
#converting the date_added column to the dd-mm-yy format
df['DATE_ADDED'] = pd.to_datetime(df['DATE_ADDED'], format='%d-%m-%Y')
print(df['DATE_ADDED'].head())

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: DATE_ADDED, dtype: datetime64[ns]

In [85]:
#3)
#Standardizing the 'COUNTRY' column
df['COUNTRY'] = df['COUNTRY'].str.split(', ')
df = df.explode('COUNTRY')
#Standardize the 'LISTED_IN' column
df['LISTED_IN'] = df['LISTED_IN'].str.split(', ')
df = df.explode('LISTED_IN')
#the result with each country and genre on its own row
print(df[['COUNTRY', 'LISTED_IN']].head())

         COUNTRY               LISTED_IN
0  United States           Documentaries
1   South Africa  International TV Shows
1   South Africa               TV Dramas
1   South Africa            TV Mysteries
2  Not Specified          Crime TV Shows

In [86]:
df.describe()

                          DATE_ADDED  RELEASE_YEAR
count                          23754  23754.000000
mean   2019-05-21 06:29:18.625915648   2013.895133
min              2008-01-01 00:00:00   1925.000000
25%              2018-04-17 00:00:00   2013.000000
50%              2019-07-12 00:00:00   2017.000000
75%              2020-08-10 00:00:00   2019.000000
max              2021-09-25 00:00:00   2021.000000
std                              NaN      8.886875

In [87]:
#detecting outliers
import pandas as pd
Q1 = df['RELEASE_YEAR'].quantile(0.25)
Q3 = df['RELEASE_YEAR'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['RELEASE_YEAR'] < lower_bound) | (df['RELEASE_YEAR'] > upper_bound)]
print("Detected outliers in 'release_year':")
print(outliers[['TITLE', 'RELEASE_YEAR']])
#Removing the outliers
df_cleaned=df[(df['RELEASE_YEAR'] >= lower_bound) & (df['RELEASE_YEAR'] <= upper_bound)]
print(f"Original DataFrame shape: {df.shape}")
print(f"Cleaned DataFrame shape: {df_cleaned.shape}")

Detected outliers in 'release_year':
            TITLE  RELEASE_YEAR
7         Sankofa          1993
7         Sankofa          1993
7         Sankofa          1993
7         Sankofa          1993
7         Sankofa          1993
...           ...           ...
8770      Yaadein          2001
8770      Yaadein          2001
8770      Yaadein          2001
8792  Young Tiger          1973
8792  Young Tiger          1973

[2027 rows x 2 columns]
Original DataFrame shape: (23754, 12)
Cleaned DataFrame shape: (21727, 12)

In [88]:
#6)
#checking for anykind of Typos or misspellings, Different spellings or abbreviations or Inconsistent capitalization
for column in df.columns:
    unique_values = df[column].unique()
    print(f"\n--- Unique values in '{column}' ---")
    print(unique_values)

--- Unique values in 'SHOW_ID' ---
['s1' 's2' 's3' ... 's8805' 's8806' 's8807']

--- Unique values in 'TYPE' ---
['Movie' 'TV Show']

--- Unique values in 'TITLE' ---
['Dick Johnson Is Dead' 'Blood & Water' 'Ganglands' ... 'Zombieland'
 'Zoom' 'Zubaan']

--- Unique values in 'DIRECTOR' ---
['Kirsten Johnson' 'Not Specified' 'Julien Leclercq' ... 'Majid Al Ansari'
 'Peter Hewitt' 'Mozez Singh']

--- Unique values in 'CAST' ---
['Not Specified'
 'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng'
 'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera'
 ...
 'Jesse Eisenberg, Woody Harrelson, Emma Stone, Abigail Breslin, Amber Heard, Bill Murray, Derek Graf'
 'Tim Allen, Courteney Cox, Chevy Chase, Kate Mara, Ryan Newman, Michael Cassidy, Spencer Breslin, Rip Torn, Kevin Zegers'
 'Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy']

--- Unique values in 'COUNTRY' ---
['United States' 'South Africa' 'Not Specified' 'India' 'Ghana'
 'Burkina Faso' 'United Kingdom' 'Germany' 'Ethiopia' 'Czech Republic'
 'Mexico' 'Turkey' 'Australia' 'France' 'Finland' 'China' 'Canada' 'Japan'
 'Nigeria' 'Spain' 'Belgium' 'South Korea' 'Singapore' 'Italy' 'Romania'
 'Argentina' 'Venezuela' 'Hong Kong' 'Russia' '' 'Ireland' 'Nepal'
 'New Zealand' 'Brazil' 'Greece' 'Jordan' 'Colombia' 'Switzerland'
 'Israel' 'Taiwan' 'Bulgaria' 'Algeria' 'Poland' 'Saudi Arabia' 'Thailand'
 'Indonesia' 'Egypt' 'Denmark' 'Kuwait' 'Netherlands' 'Malaysia' 'Vietnam'
 'Hungary' 'Sweden' 'Lebanon' 'Syria' 'Philippines' 'Iceland'
 'United Arab Emirates' 'Norway' 'Qatar' 'Mauritius' 'Austria' 'Cameroon'
 'Palestine' 'Uruguay' 'United Kingdom,' 'Kenya' 'Chile' 'Luxembourg'
 'Cambodia' 'Bangladesh' 'Portugal' 'Cayman Islands' 'Senegal' 'Serbia'
 'Malta' 'Namibia' 'Angola' 'Peru' 'Mozambique' 'Cambodia,' 'Belarus'
 'Zimbabwe' 'Puerto Rico' 'Pakistan' 'Cyprus' 'Guatemala' 'Iraq' 'Malawi'
 'Paraguay' 'Croatia' 'Iran' 'West Germany' 'United States,' 'Albania'
 'Georgia' 'Soviet Union' 'Morocco' 'Slovakia' 'Ukraine' 'Bermuda'
 'Ecuador' 'Armenia' 'Mongolia' 'Bahamas' 'Sri Lanka' 'Latvia'
 'Liechtenstein' 'Cuba' 'Nicaragua' 'Poland,' 'Slovenia'
 'Dominican Republic' 'Samoa' 'Azerbaijan' 'Botswana' 'Vatican City'
 'Jamaica' 'Kazakhstan' 'Lithuania' 'Afghanistan' 'Somalia' 'Sudan'
 'Panama' 'Uganda' 'East Germany' 'Montenegro']

--- Unique values in 'DATE_ADDED' ---
<DatetimeArray>
['2021-09-25 00:00:00', '2021-09-24 00:00:00', '2021-09-23 00:00:00',
 '2021-09-22 00:00:00', '2021-09-21 00:00:00', '2021-09-20 00:00:00',
 '2021-09-19 00:00:00', '2021-09-17 00:00:00', '2021-09-16 00:00:00',
 '2021-09-15 00:00:00',
 ...
 '2018-09-27 00:00:00', '2017-03-23 00:00:00', '2016-12-25 00:00:00',
 '2016-11-30 00:00:00', '2017-10-23 00:00:00', '2017-11-04 00:00:00',
 '2015-08-05 00:00:00', '2018-12-06 00:00:00', '2016-03-09 00:00:00',
 '2020-01-11 00:00:00']
Length: 1699, dtype: datetime64[ns]

--- Unique values in 'RELEASE_YEAR' ---
[2020 2021 1993 2018 1996 1998 1997 2010 2013 2017 1975 1978 1983 1987
 2012 2001 2014 2002 2003 2004 2011 2008 2009 2007 2005 2006 1994 2015
 2019 2016 1982 1989 1990 1991 1999 1986 1992 1984 1980 1961 2000 1995
 1985 1976 1959 1988 1981 1972 1964 1945 1954 1979 1958 1956 1963 1970
 1973 1925 1974 1960 1966 1971 1962 1969 1977 1967 1968 1965 1946 1942
 1955 1944 1947 1943]

--- Unique values in 'RATING' ---
['PG-13' 'TV-MA' 'PG' 'TV-14' 'TV-PG' 'TV-Y' 'TV-Y7' 'R' 'TV-G' 'G'
 'NC-17' '74 min' '84 min' '66 min' 'NR' nan 'TV-Y7-FV' 'UR']

--- Unique values in 'DURATION' ---
['90 min' '2 Seasons' '1 Season' '91 min' '125 min' '9 Seasons' '104 min'
 '127 min' '4 Seasons' '67 min' '94 min' '5 Seasons' '161 min' '61 min'
 '166 min' '147 min' '103 min' '97 min' '106 min' '111 min' '3 Seasons'
 '110 min' '105 min' '96 min' '124 min' '116 min' '98 min' '23 min'
 '115 min' '122 min' '99 min' '88 min' '100 min' '6 Seasons' '102 min'
 '93 min' '95 min' '85 min' '83 min' '113 min' '13 min' '182 min' '48 min'
 '145 min' '87 min' '92 min' '80 min' '117 min' '128 min' '119 min'
 '143 min' '114 min' '118 min' '108 min' '63 min' '121 min' '142 min'
 '154 min' '120 min' '82 min' '109 min' '101 min' '86 min' '229 min'
 '76 min' '89 min' '156 min' '112 min' '107 min' '129 min' '135 min'
 '136 min' '165 min' '150 min' '133 min' '70 min' '84 min' '140 min'
 '78 min' '7 Seasons' '64 min' '59 min' '139 min' '69 min' '148 min'
 '189 min' '141 min' '130 min' '138 min' '81 min' '132 min' '10 Seasons'
 '123 min' '65 min' '68 min' '66 min' '62 min' '74 min' '131 min' '39 min'
 '46 min' '38 min' '8 Seasons' '17 Seasons' '126 min' '155 min' '159 min'
 '137 min' '12 min' '273 min' '36 min' '34 min' '77 min' '60 min' '49 min'
 '58 min' '72 min' '204 min' '212 min' '25 min' '73 min' '29 min' '47 min'
 '32 min' '35 min' '71 min' '149 min' '33 min' '15 min' '54 min' '224 min'
 '162 min' '37 min' '75 min' '79 min' '55 min' '158 min' '164 min'
 '173 min' '181 min' '185 min' '21 min' '24 min' '51 min' '151 min'
 '42 min' '22 min' '134 min' '177 min' '13 Seasons' '52 min' '14 min'
 '53 min' '8 min' '57 min' '28 min' '50 min' '9 min' '26 min' '45 min'
 '171 min' '27 min' '44 min' '146 min' '20 min' '157 min' '17 min'
 '203 min' '41 min' '30 min' '194 min' '15 Seasons' '233 min' '237 min'
 '230 min' '195 min' '253 min' '152 min' '190 min' '160 min' '208 min'
 '180 min' '144 min' '5 min' '174 min' '170 min' '192 min' '209 min'
 '187 min' '172 min' '16 min' '186 min' '11 min' '193 min' '176 min'
 '56 min' '169 min' '40 min' '10 min' '3 min' '168 min' '312 min'
 '153 min' '214 min' '31 min' '163 min' '19 min' '12 Seasons' nan
 '179 min' '11 Seasons' '43 min' '200 min' '196 min' '167 min' '178 min'
 '228 min' '18 min' '205 min' '201 min' '191 min']

--- Unique values in 'LISTED_IN' ---
['Documentaries' 'International TV Shows' 'TV Dramas' 'TV Mysteries'
 'Crime TV Shows' 'TV Action & Adventure' 'Docuseries' 'Reality TV'
 'Romantic TV Shows' 'TV Comedies' 'TV Horror' 'Children & Family Movies'
 'Dramas' 'Independent Movies' 'International Movies' 'British TV Shows'
 'Comedies' 'Spanish-Language TV Shows' 'Thrillers' 'Romantic Movies'
 'Music & Musicals' 'Horror Movies' 'Sci-Fi & Fantasy' 'TV Thrillers'
 "Kids' TV" 'Action & Adventure' 'TV Sci-Fi & Fantasy' 'Classic Movies'
 'Anime Features' 'Sports Movies' 'Anime Series' 'Korean TV Shows'
 'Science & Nature TV' 'Teen TV Shows' 'Cult Movies' 'TV Shows'
 'Faith & Spirituality' 'LGBTQ Movies' 'Stand-Up Comedy' 'Movies'
 'Stand-Up Comedy & Talk Shows' 'Classic & Cult TV']

--- Unique values in 'DESCRIPTION' ---
['As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.'
 'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.'
 'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.'
 ...
 'Looking to survive in a world taken over by zombies, a dorky college student teams with an urban roughneck and a pair of grifter sisters.'
 'Dragged from civilian life, a former superhero must train a new crop of youthful saviors when the military preps for an attack by a familiar villain.'
 "A scrappy but poor boy worms his way into a tycoon's dysfunctional family, while facing his fear of music and the truth about his past."]

In [89]:
#Cleaned version of the Dataset.
print(df.shape)
df.head()

(23754, 12)

,SHOW_ID,TYPE,TITLE,DIRECTOR,CAST,COUNTRY,DATE_ADDED,RELEASE_YEAR,RATING,DURATION,LISTED_IN,DESCRIPTION
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Specified,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Not Specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,International TV Shows,"After crossing paths at a party, a Cape Town t..."
1,s2,TV Show,Blood & Water,Not Specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,TV Dramas,"After crossing paths at a party, a Cape Town t..."
1,s2,TV Show,Blood & Water,Not Specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,TV Mysteries,"After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Not Specified,2021-09-24,2021,TV-MA,1 Season,Crime TV Shows,To protect his family from a powerful drug lor...